AWSTemplateFormatVersion: '2010-09-09'

Resources:
  pvdhagenTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08e2d37b6a0129927
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref HTTPSecurityGroup
      Tags:
        - Key: git_last_modified_by
          Value: pvondemhagen@yahoo.com
        - Key: git_last_modified_at
          Value: "2023-02-01 22:01:40"
        - Key: git_file
          Value: test-stack.yaml
        - Key: git_commit
          Value: a0dc794787fb7de63f7f55a6314ff6487420c21c
        - Key: yor_trace
          Value: 0698392e-676e-46a6-a3ac-1ee264291361
        - Key: git_repo
          Value: aws_cloud_formation_3
        - Key: git_org
          Value: pvondemhagen
        - Key: git_modifiers
          Value: pvondemhagen
      Tenancy: default
      SubnetId: subnet-06ebbd4e2923f4074
      EbsOptimized: False
      SourceDestCheck: True
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            Encrypted: False
            VolumeSize: 8
            SnapshotId: snap-09929113cb22f4007
            VolumeType: gp2
            DeleteOnTermination: True
      HibernationOptions:
        Configured: False
      EnclaveOptions:
        Enabled: False


  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80  and port 443
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
      Tags:
        - Key: git_last_modified_at
          Value: "2023-02-01 22:01:40"
        - Key: git_file
          Value: test-stack.yaml
        - Key: git_commit
          Value: a0dc794787fb7de63f7f55a6314ff6487420c21c
        - Key: yor_trace
          Value: 86a291e4-4475-4eed-8a48-fd188d674a5c
        - Key: git_repo
          Value: aws_cloud_formation_3
        - Key: git_org
          Value: pvondemhagen
        - Key: git_modifiers
          Value: pvondemhagen
        - Key: git_last_modified_by
          Value: pvondemhagen@yahoo.com
